name: web-aplikacija
base: core24
version: '0.1'
summary: Simple Flask App
# Detailed description of the application
description: |
  This is a simple Flask application that says "Hello, World!".

grade: devel
confinement: devmode

parts:
  web-aplikacija:
    plugin: python
    source: .
    python-requirements: ['requirements.txt']

  run-flask-script:
    plugin: dump
    source: .
    organize:
      run-flask.sh: bin/run-flask.sh # Map the script to the bin directory


apps:
  web-aplikacija:
    command: bin/run-flask.sh
    plugs:
      - network-bind
