name: pygame-frame-demo
base: core24
version: "0.1"
summary: Pygame app on Ubuntu Core + Ubuntu Frame (Wayland)
description: |
  Pygame (SDL2) aplikacija pokrenuta na Ubuntu Core-u kroz Ubuntu Frame (Wayland),
  pakirana kao strict snap koristeći Canonical wayland-launch i gpu-2404.

grade: stable
confinement: strict
compression: lzo

apps:
  pygame-frame-demo:
    command-chain:
      - bin/gpu-2404-wrapper
      - bin/wayland-launch

    # Snapcraft najbolje: command + args (umjesto "command: bin/python3 $SNAP/...")
    command: bin/python3 $SNAP/app/main.py

    daemon: simple
    restart-condition: always
    restart-delay: 3s
    plugs:
      - wayland
      - opengl
      - gpu-2404
      - desktop
      - audio-playback

    environment:
      # SDL2/Pygame: Wayland
      SDL_VIDEODRIVER: wayland
      SDL_VIDEO_WAYLAND_ALLOW_LIBDECOR: "0"
      # ako ti ne treba audio
      SDL_AUDIODRIVER: dummy

      # XDG
      XDG_DATA_HOME: $SNAP_USER_DATA
      XDG_DATA_DIRS: $SNAP/usr/local/share:$SNAP/usr/share

plugs:
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404

environment:
  XDG_CACHE_HOME: $SNAP_USER_COMMON/.cache
  XDG_CONFIG_HOME: $SNAP_USER_DATA/.config
  XDG_CONFIG_DIRS: $SNAP/etc/xdg
  XDG_DATA_DIRS: $SNAP/usr/local/share:$SNAP/usr/share
  XKB_CONFIG_ROOT: $SNAP/usr/share/X11/xkb
  XKB_CONFIG_EXTRA_PATH: $SNAP/usr/share/X11/xkb

layout:
  # GPU userspace (mesa-2404)
  /usr/share/libdrm:
    bind: $SNAP/gpu-2404/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/gpu-2404/drirc.d

  # XKB data (FIX za "Failed to create XKB context")
  /usr/share/X11/xkb:
    bind: $SNAP/usr/share/X11/xkb

  # Fontovi i osnovni resursi
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /etc/fonts:
    bind: $SNAP/etc/fonts

parts:
  # 1) Pygame app
  app:
    plugin: python
    source: super-mario-python
    python-packages:
      - pygame==2.6.1
      - numpy==1.26.4
      - scipy==1.11.4
    override-build: |
      craftctl default
      install -d "$CRAFT_PART_INSTALL/app"
      cp -a "$CRAFT_PART_SRC/." "$CRAFT_PART_INSTALL/app/"

    stage-packages:
      # SDL2 runtime
      - libsdl2-2.0-0

      # Wayland + XKB runtime (BITNO)
      - libxkbcommon0
      - xkb-data
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1

      # audio config (ako koristiš audio; ako ti ne treba, možeš izbaciti ove)
      - libasound2t64
      - libasound2-data
      - alsa-topology-conf
      - alsa-ucm-conf

  # 2) Wayland helperi (wayland-launch)
  setup:
    plugin: dump
    source: wayland-launch
    override-build: |
      set -e
      PLUGS="opengl wayland gpu-2404"
      sed --in-place "s/%PLUGS%/$PLUGS/g" "$CRAFT_PART_BUILD/bin/wayland-launch"
      sed --in-place "s/%PLUGS%/$PLUGS/g" "$CRAFT_PART_BUILD/bin/setup.sh"
      chmod 755 "$CRAFT_PART_BUILD/bin/wayland-launch" "$CRAFT_PART_BUILD/bin/setup.sh"
      craftctl default
    stage-packages:
      - inotify-tools

  # 3) GPU wrapper (gpu-2404)
  gpu-2404:
    after: [setup]
    plugin: dump
    source: https://github.com/canonical/gpu-snap.git
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
      cd "$CRAFT_PRIME/usr/share/" || exit 0
      rm -rf bug drirc.d glvnd libdrm lintian man || true
      rm -rf applications apport bash-completion dbus-1 doc-base doc gtk-doc\ help pkgconfig libthai metainfo themes thumbnailers xml || true
    prime:
      - bin/gpu-2404-wrapper

platforms:
  amd64:
  arm64:
  armhf:
